# Generated by Django 5.2.1 on 2025-05-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_faculty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('BBA', 'BBA'), ('English', 'English'), ('LLB', 'LLB'), ('Architecture', 'Architecture')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], default='Student', max_length=10),
        ),
    ]
