# Generated by Django 5.2.1 on 2025-05-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='department_name',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('BBA', 'Bachelor of Business Administration'), ('SWE', 'Software Engineering'), ('Civil', 'Civil Engineering'), ('Architecture', 'Architecture'), ('Textile', 'Textile Engineering'), ('Agriculture', 'Agriculture'), ('ENG', 'English'), ('ECN', 'Economics'), ('PHY', 'Physics'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IPE', 'Industrial and Production Engineering'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
