# Generated by Django 5.2.1 on 2025-05-30 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_rating_comment_alter_rating_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='StarRating',
        ),
    ]
