# Generated by Django 5.2.1 on 2025-06-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_rename_rating_starrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
