# Generated by Django 5.2.1 on 2025-06-23 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_noterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the faculty member.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Select the faculty who taught the course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.faculty'),
        ),
    ]
