# Generated by Django 5.2.1 on 2025-06-23 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_faculty_note_faculty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_contribution_count', models.PositiveIntegerField(default=0, help_text='Total number of approved notes contributed by the user.')),
                ('average_star_rating', models.FloatField(default=0.0, help_text='Average rating of all approved notes from the user.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contributor Profile',
                'verbose_name_plural': 'Contributor Profiles',
                'ordering': ['-note_contribution_count', '-average_star_rating'],
            },
        ),
    ]
