# Generated by Django 5.2.1 on 2025-06-24 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department to which the faculty belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='notes.department'),
        ),
    ]
