# Generated by Django 5.2.1 on 2025-06-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_faculty_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the faculty member.', max_length=255, null=True),
        ),
    ]
