# Generated by Django 5.2.1 on 2025-08-08 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='noterequest',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, help_text='The user who fulfilled this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noterequest',
            name='fulfilled_note',
            field=models.OneToOneField(blank=True, help_text='The note that was uploaded to fulfill this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_request', to='notes.note'),
        ),
        migrations.AlterField(
            model_name='noterequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='noterequest',
            name='user',
            field=models.ForeignKey(help_text='The user who requested the note.', on_delete=django.db.models.deletion.CASCADE, related_name='note_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
