# Generated by Django 5.2.1 on 2025-05-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text="User's primary department", max_length=100, null=True),
        ),
    ]
