# Generated by Django 5.2.1 on 2025-05-25 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Student ID must be in the format: 'XXX-XXX-XXX' (e.g., 222-115-141).", regex='^\\d{3}-\\d{3}-\\d{3}$')]),
        ),
    ]
